#!/bin/bash
#to change hostname
servername=lab
echo "you are going to set hostname is $servername"
echo "$servername" >/etc/hostname

#privateip=$((ifconfig eth0 | grep -w 'inet' | awk '{print $2}'))
privateip=$(hostname -I)
echo "$privateip $servername" >>/etc/hosts
hostname -F /etc/hostname
echo "your servername is :`hostname` "
echo "your servername is :$HOSTNAME "
cd /tmp/
yum install wget unzip -y
wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
rpm -ivh jdk-8u131-linux-x64.rpm
wget http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32-windows-x64.zip
unzip apache-tomcat-8.5.32-windows-x64.zip
mv apache-tomcat-8.5.32 /opt/tomcat
chmod -R 755 /opt/tomcat/
rm -rf /opt/tomcat/webapps/*
sed -i 's/8080/80/g' /opt/tomcat1/conf/server.xml
/opt/tomcat/bin/startup.sh
wget http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
rpm -ivh mysql57-community-release-el7-7.noarch.rpm
yum install mysql-server*
service mysqld start
